import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import ClientNavbar from "@/components/ClientNavbar"; // Import ClientNavbar

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ClientNavbar />
          <div >{children}</div> {/* Adjust padding based on Navbar height */}
        </body>
      </AuthProvider>
    </html>
  );
}
